# Window Customization
[window]
opacity = 1
dimensions = { columns = 140, lines = 38 }
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

# Font Customization
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

# Default colors
[colors.primary]
background = "#000000"
