[colors]
draw_bold_text_with_bright_colors = true

# Kanagawa Theme
[colors.primary]
 background = "#1f1f28"
 foreground = "#dcd7ba"

[colors.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[colors.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

[colors.selection]
text = "#c8c093"
background = "#2d4f67"

[font]
size = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "SemiBold"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 0
