separator=false
markup=pango

[calendar]
command=~/.config/i3/blocklets/calendar.sh
interval=1
min_width=900
LABEL= 
DATEFMT=+%a %d-%m-%Y %H:%M
# SHORTFMT=+%H:%M:%S
HEIGHT=180
WIDTH=220

[volume]
command=~/.config/i3/blocklets/volume.sh
interval=1
signal=1
LONG_FORMAT=${SYMB}${VOL}%

[kbdd_layout]
command=~/.config/i3/blocklets/kbdd_layout.sh
interval=persist
